name: Package pytoshop for Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install pytoshop
      run: pip install --target ./pytoshop_package pytoshop==1.1.0 -I --no-cache-dir

    - name: Install pytoshop twice
      run: pip install --target ./pytoshop_package pytoshop==1.1.0 -I --no-cache-dir

    - name: Create ZIP file
      run: tar -zcvf pytoshop_windows.zip pytoshop_package

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: pytoshop_windows
        path: pytoshop_windows.zip
