name: Package pytoshop for Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install Cython
      run: pip install cython

    - name: Clone pytoshop repository
      run: git clone https://github.com/mdboom/pytoshop.git

    - name: Install pytoshop
      run: |
        cd pytoshop
        python setup.py install --prefix=./pytoshop_package

    - name: Create ZIP file
      run: Compress-Archive -Path pytoshop_package -DestinationPath pytoshop_windows.zip
      shell: pwsh

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: pytoshop_windows
        path: pytoshop_windows.zip
